### ISSUE TITLE
netbox_ipam_prefix parsing time error when applying

### ISSUE THREAD

**Issue by dsears3463** [smutel/terraform-provider-netbox#113]
## Summary

When running apply, terraform errors with "Error: parsing time "2022-05-17T17:37:40.748725Z": extra text: "T17:37:40.748725Z" error (timestamp changes based on run time).
### Netbox version

```paste below
3.2.3
```

### Terraform version

```paste below
1.0.8
```

### Provider version

```paste below
3.1.0
```

### Affected Data(s) / Resource(s)

* resource netbox_ipam_prefix

### Terraform Configuration Files

```hcl
resource "netbox_ipam_prefix" "prefix" {
  description = "Test description"
  is_pool     = true
  prefix      = "192.168.56.0/24"
  status      = "active"
}
```

### Terraform Output

```paste below
netbox_ipam_prefix.prefix: Creating...
╷
│ Error: parsing time "2022-05-17T17:37:40.748725Z": extra text: "T17:37:40.748725Z"
│
│   with netbox_ipam_prefix.prefix,
│   on main.tf line 3, in resource "netbox_ipam_prefix" "prefix":
│    3: resource "netbox_ipam_prefix" "prefix" {
│
╵
```

### Actual Behavior

Resource is created but state file isn't being set/updated as terraform is encountering an error.
### Expected Behavior

Resource is created and state file is updated to match.
### Steps to Reproduce

1. `terraform apply`

**Comment by smutel** [comment]
https://github.com/smutel/terraform-provider-netbox#compatibility-with-netbox
