### ISSUE TITLE
Error: parsing time "2022-06-23T11:31:54.513042Z": extra text: "T11:31:54.513042Z"

### ISSUE THREAD

**Issue by devogs** [smutel/terraform-provider-netbox#128]
## Summary

After apply validated I get this error:

 Error: parsing time "2022-06-23T11:31:54.513042Z": extra text: "T11:31:54.513042Z"

### Netbox version

```paste below
Netbox v3.2.1
```

### Terraform version

```paste below
Terraform v1.2.3
```

### Provider version

```paste below
 provider registry.terraform.io/smutel/netbox v4.0.1
```

### Affected Data(s) / Resource(s)

All

### Terraform Configuration Files

```hcl

```

### Terraform Output

```paste below
 Error: parsing time "2022-06-23T11:44:14.430735Z": extra text: "T11:44:14.430735Z"
│
│   with netbox_tenancy_tenant_group.tenant_group_test,
│   on main.tf line 27, in resource "netbox_tenancy_tenant_group" "tenant_group_test":
│   27: resource "netbox_tenancy_tenant_group" "tenant_group_test" {
│

```

### Steps to Reproduce

1. `terraform apply`

**Comment by zteeed** [comment]
Me too ^^

**Comment by zteeed** [comment]
@michalg91, what netbox version and terraform plugin version was working for you ?

**Comment by michalg91** [comment]
@zteeed it was working with netbox 2.11 and some sort of 2.x plugin.
We've upgraded netbox to 3.2 few weeks ago and since then our terraforms are broken so, for now we stopped using this plugin.

**Comment by Sabrimjd** [comment]
Hello, This provider is not compatible with netbox 3.2 yet.
