### ISSUE TITLE
Updated to support Netbox 3.4.x

### ISSUE THREAD

**Issue by bab3l** [smutel/terraform-provider-netbox#186]
## Summary
Please provide a build that supports the Netbox 3.4.x API. I'm hoping to use this provider, but unfortunately am already running on a 3.4.x release of Netbox.

**Comment by amhn** [comment]
Do you have any specific errors using the provider with 3.4? I've been using it for some time with 3.4 and it (mostly) works.

Explicit support for 3.4 would be nice.
