### ISSUE TITLE
Improve (and fix) tests for custom fields

### ISSUE THREAD

**Issue by amhn** [smutel/terraform-provider-netbox#204]
## Summary

Several improvements can be made to the tests for the custom fields.

The most important is to test the created field with an object the field is assigned to.
This lead me to discover some issues:
- object field is incorrectly sent as list to netbox
- choices in netbox 3.5 is mandatory for select, multiselect
- if a select custom field is modified, but choices is unchanged, a null value is sent for choices

**Comment by smutel** [comment]
Hello @amhn,

`choices in netbox 3.5 is mandatory for select, multiselect`

Is this compatible with Netbox 3.3 / 3.4 ?

**Comment by smutel** [comment]
@amhn ?
