### ISSUE TITLE
I am not able to do use the terraform provider

### ISSUE THREAD

**Issue by mdomore** [smutel/terraform-provider-netbox#226]
## Issue description
I am having a error when trying use the provider. It was working fine on 10/06/2023 4:02 PM (CEST)
Not working anymore on 10/06/2023 4:02 PM (CEST)

Here is the error : 

│ Error: Failed to install provider
│ 
│ Error while installing smutel/netbox v7.1.0: error checking signature:
│ openpgp: key expired

### Netbox version
v3.4.10

### Terraform version
Terraform v1.6.0

### Provider version
version 7.1.0

**Comment by smutel** [comment]
Hello,

Sorry for the inconvenience, I am not able to update the GPG key myself on registry.terraform.io.
I sent an e-mail to hashicorp for assistance.

Regards,

**Comment by smutel** [comment]
I found this:
- https://github.com/hashicorp/terraform/issues/33984
- https://github.com/hashicorp/terraform/issues/33984

And I tried with terraform 1.5.7 and it works perfectly.

**Comment by mdomore** [comment]
Thanks for the links. Rolled back to old version for the moment.

**Comment by smutel** [comment]
Bug fixed in https://github.com/hashicorp/terraform/releases/tag/v1.6.1.
