### ISSUE TITLE
Looking for help on getting the "next available" IP in a prefix

### ISSUE THREAD

**Issue by pezhore** [smutel/terraform-provider-netbox#45]
### What I want to do
I'd like to provide a prefix network (e.g. `10.80.1.0/24`) and then get the next available IP in that prefix. From the look of the `netbox_ipam_ip_addresses` resource, the address is mandatory - so I'd assume I'd need some data providers to identify the available IPs for a prefix.

The API call to get this "next available" is fairly straightforward:

```
GET /api/ipam/prefixes/37/available-ips/?limit=1

HTTP 200 OK
Allow: GET, POST, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

[
    {
        "family": 4,
        "address": "10.80.1.2/24",
        "vrf": null
    }
]
```

From playing around in Postman, you just need to get the prefix ID (in my example the `10.80.1.0/24` prefix is id `37`), then query for `available-ips`, limiting to 1 (or really whatever the terraform `count` would be I suppose.

### What I already test

1. Tried dumping the data content of the `json_ipam_prefixes_list` to see if there was something there.
2. Identified the API calls to achieve this effort

### Netbox version

```paste below
v2.10.3
```

### Terraform version

```paste below
v0.14.6
```

### Provider version

```paste below
1.2.0
```

**Comment by smutel** [comment]
Hello,

It will be an interesting feature.

I am using the go-netbox library to develop this provider. I am not sure it's enough to develop this feature.

I need to look at this more deeply.

**Comment by But4ler** [comment]
Hello, currently, we have a bash for this need
If it helps, the curl request:
`
curl -k -s -X POST \
      --header 'Content-Type: application/json' \
      --header 'Accept: application/json; indent=4' \
      --header "Authorization: Token $Token" \
       -d '{ "description": "'"$description"'" }' \
               "https://$netbox_host/api/ipam/prefixes/$prefix/available-ips/
`

**Comment by pezhore** [comment]
@But4ler if you throw a `?limit=1` at the end of the url, it'll just return one IP. With some translation, I'm guessing you could key off the `count` resource primitive to return the required number of IPs.

**Comment by IlyaKochnev** [comment]
Hi @pezhore ,
I do this the next way
`
locals {
  next_ip     = jsondecode(data.http.available-ip.body)[0].address
  prefix_id = jsondecode(data.http.prefix_id.body).results[0].id
}

data "http" "available-ip" {
  url = "https://${var.netbox_server}/api/ipam/prefixes/${local.prefix_id}/available-ips/?limit=1"

  request_headers = {
    Accept        = "application/json; indent=4",
    Authorization = "Token ${data.vault_generic_secret.common_secrets.data["netbox_ro_token"]}"
  }
}

data "http" "prefix_id" {
  url = "https://${var.netbox_server}/api/ipam/prefixes/?vlan_id=${data.netbox_ipam_vlan.vlan.id}&limit=1"

  request_headers = {
    Accept        = "application/json; indent=4",
    Authorization = "Token ${data.vault_generic_secret.common_secrets.data["netbox_ro_token"]}"
  }
}

data "netbox_ipam_vlan" "vlan" {
  vlan_id       = var.vlan_id
  vlan_group_id = data.netbox_ipam_vlan_group.vlan_group.id
}

data "netbox_ipam_vlan_group" "vlan_group" {
  slug    = "${var.dc}_vlans"
  site_id = data.netbox_dcim_site.site.id
}

data "netbox_dcim_site" "site" {
  slug = "${var.dc}-${var.dc_name[var.dc]}"
}
`
Hope this helps

**Comment by pezhore** [comment]
Thanks @IlyaKochnev, I ended up doing a PR against a different provider with this functionality, but that solution would definitely be a valid workaround.

**Comment by amhn** [comment]
I would look into this functionality.

I'm not sure if this is new, but in Netbox 3.2 you can send a POST request to the endpoint and get a newly created IP address.

The way I would do it is changing the IP address resource. It could be changed to also accept a prefix id (or even an ip range id) instead of an address, ask netbox for an available IP in this prefix and then fill the IP object with the data from the schema. The swagger.json needs to be patched because the available IP function behaves different than documented (See https://github.com/netbox-community/netbox/issues/10311).

Changing the prefix would force a recreation. Other changes should behave like the IP address resource.

Do you think this approach could work?

If this works, the same can be done for AvailablePrefix.
