### ISSUE TITLE
SSL - Allow untrust authority

### ISSUE THREAD

**Issue by But4ler** [smutel/terraform-provider-netbox#46]
## Summary
Hello,

If possible, it should be possible to authorize SSL certificates signed by a private CA. 

### Terraform code

```hcl
provider netbox {
  url = "<fqdn>"
  token = "........"
  scheme = "https"
  ssl_verify = false
}

resource "netbox_ipam_ip_addresses" "ip_test" {
  address = "10.80.10.0/24"
  description = "IP created by terraform"
  status = "active"
}
```

### Tasks executed by this terraform code

Execution of the terraform code without checking the cert validity.

Thanks !

**Comment by smutel** [comment]
Hello,

I can look to add an option to not verify the cert.

But as workaround could you please try to add your CA into the system where you are executed the terraform command and try again?

If you are using a Linux to execute terraform you can add it to `/usr/local/share/ca-certificates` and execute `update-ca-certificates` command.

**Comment by duviful** [comment]
Hello, I'm also interested in this feature.
I'm running MacOS and I would like to help.

I've added the certificate in the system keychains and set to always trust. Safari browser likes it.
Still, I'm getting this error on terraform apply:

`Error: Post "https://xxxxxx.xxxx.xxxxx.com/api/virtualization/virtual-machines/": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0`

Thanks !

**Comment by smutel** [comment]
Can someone test the branch `AddInsecureOption` and tell me if it is working as expected ?
