### ISSUE TITLE
Allow managing of IPv6 addresses

### ISSUE THREAD

**Issue by amhn** [smutel/terraform-provider-netbox#50]
## Summary

Change ValidateFunc for IP addresses to allow IPv6 addresses.

### Usage

Allow managing IPv6 addresses via terraform. It is already possible to add IPv6 prefixes via netbox_ipam_prefix.

### Terraform code

```hcl
resource "netbox_ipam_ip_addresses" "ip_test" {
  address = "2001:DB8::1/32"
}
```

For a possible implementation, see https://github.com/amhn/terraform-provider-netbox/commit/92d5438e398a4dea52f0269368abd958891fb000
Tested with terraform 0.13.6 and 0.14.8 and netbox 3e4c35ffd9f6 (v2.10.6)

**Comment by smutel** [comment]
Hello. Could you please open a PR ? Thanks.
