### ISSUE TITLE
ipam_service port list is not read or created

### ISSUE THREAD

**Issue by amhn** [smutel/terraform-provider-netbox#52]
## Summary

ports for ipam_service are returned as list from netbox. Terraform expects a string. The field in the JSON output from netbox has been renamed from `port` to `ports`.

### Netbox version

```paste below
3e4c35ffd9f6 (v2.10.6)
```

### Terraform version

```paste below
Terraform v0.14.8
```

### Provider version

master (https://github.com/smutel/terraform-provider-netbox/commit/39ac08b80d17bfb8622e8428d205ceb9adcb45f7)

### Affected Data(s) / Resource(s)

* resource ipam_service

### Terraform Configuration Files

```hcl
resource "netbox_ipam_service" "service_test" {
  name = "test-service"
  port = 8081
  protocol = "tcp"
  virtualmachine_id = 1
}
```

### Terraform Output

```paste below
Terraform will perform the following actions:

  # netbox_ipam_service.service_test will be created
  + resource "netbox_ipam_service" "service_test" {
      + description       = " "
      + id                = (known after apply)
      + name              = "test-service"
      + port              = 8081
      + protocol          = "tcp"
      + virtualmachine_id = 1
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

netbox_ipam_service.service_test: Creating...

Error: [POST /ipam/services/][400] ipam_services_create default  map[ports:[This field is required.]]

  on netbox.tf line 86, in resource "netbox_ipam_service" "service_test":
  86: resource "netbox_ipam_service" "service_test" {

```

### Actual Behavior

ipam_service creation fails due to missing ports argument. If imported (see #51 ) the state shows an empty port variable and setting port has no effect in netbox.

### Expected Behavior

Service can be created and ports can be read back from netbox

### Steps to Reproduce

1. `terraform apply`

## Fixes
See https://github.com/amhn/terraform-provider-netbox/commit/7b801ea7d0872aeed7c71d56424af9415f8f672b for a working version.
I have no experience with go, so I had to disable the validate functions in vendor/github.com/netbox-community/go-netbox/netbox/models/service.go and vendor/github.com/netbox-community/go-netbox/netbox/models/writable_service.go.

**Comment by smutel** [comment]
Hello,

Currently this provider is using the go-netbox library which is for netbox 2.9 only.
The community around go-netbox is not really active ...

Each major version of this provider is for one version of netbox.
I keep this issue opened and will see if it's still there with go-netbox for netbox 2.10.

Regards,
