### ISSUE TITLE
local_context_data on virtual machine is asking for a string but needs te be JSON

### ISSUE THREAD

**Issue by caskalverboer** [smutel/terraform-provider-netbox#59]
## Summary

I can't use local_context_data on a virtual machine because the module asks for a string but the API for JSON.
### Netbox version

```paste below
v2.9.9
```

### Terraform version

```paste below
0.15.1
```

### Provider version

```paste below
1.3.0
```

### Affected Data(s) / Resource(s)

* resource netbox_virtualization_vm

### Terraform Configuration Files

```hcl
resource "netbox_virtualization_vm" "vm" {
  name            = vsphere_virtual_machine.vm.name
  disk            = vsphere_virtual_machine.vm.disk[0].size
  memory          = vsphere_virtual_machine.vm.memory
  cluster_id      = 4
  local_context_data = {"test": "test"}

  tag {
    name = "all"
    slug = "all"
  }

}

```

### Terraform Output

```paste below
When using a dict:
│ Error: Incorrect attribute value type
│ 
│   on vm.tf line 78, in resource "netbox_virtualization_vm" "vm":
│   78:   local_context_data = {"test": "test"} 
│ 
│ Inappropriate value for attribute "local_context_data": string required.

When using a string:
╷
│ Error: [POST /virtualization/virtual-machines/][400] virtualization_virtual-machines_create default  map[local_context_data:[JSON data must be in object form. Example: {"foo": 123}]]
│ 
│   on vm.tf line 73, in resource "netbox_virtualization_vm" "vm":
│   73: resource "netbox_virtualization_vm" "vm" {
│ 
```
### Actual Behavior

The module only accepting a string for local_context_data meanwhile the API needs it in JSON format.
### Expected Behavior

The module accepting JSON format for local_context_data
### Steps to Reproduce

1. `terraform plan`
2. Terraform apply

**Comment by S0LERA** [comment]
Hi, I am having the same behaviour with the new version (3.0.0) of the provider. If I specify the local_context_data, an error 400 occurs:

```hcl
resource "netbox_virtualization_vm" "vm_test" {
  name = test
  cluster_id = 1
  local_context_data = "{\"test\": \"test\"}"
}
```

```
Error: response status code does not match any response statuses defined for this endpoint in the swagger spec (status 400): {}
```

I tried with and without double quotes: `local_context_data = "{test: test}"`

And, if json is specified instead of string (`local_context_data = {"test": "test"}`), a type error occurs:
```
Inappropriate value for attribute "local_context_data": string required.
```
