### ISSUE TITLE
VM Creation fails after parsing issue

### ISSUE THREAD

**Issue by HerrTxbias** [smutel/terraform-provider-netbox#60]
## Summary
After a VM is created, there is an error parsing the values. However, the VM itself is created without problems.

### Netbox version
```
v2.11.3
```

### Terraform version
```
v0.15.3
```

### Provider version
```
v1.3.0
```

### Affected Data(s) / Resource(s)
* resource netbox_virtualization_vm

### Terraform Configuration Files
```hcl
resource "netbox_virtualization_vm" "virtual_machines" {
  for_each = local.qemu_vms_dict

  name = each.value.name
  role_id = 1
  cluster_id = var.pm_cluster_id
  tenant_id = 1
  platform_id = 0
  status = "active"

  vcpus = each.value.cpus
  memory = ceil(each.value.maxmem / (1.049*pow(10, 6)))
  disk = ceil(each.value.maxdisk / (1.074*pow(10, 9)))
}
```

### Terraform Output
```
╷
│ Error: json: cannot unmarshal string into Go struct field VirtualMachineWithConfigContext.vcpus of type int64
│
│   with netbox_virtualization_vm.virtual_machines["6350edaa02b8352a6d31a5b11cda28b5"],
│   on main.tf line 54, in resource "netbox_virtualization_vm" "virtual_machines":
│   54: resource "netbox_virtualization_vm" "virtual_machines" {
│
╵
```

### Actual Behavior
The Scripts emits an error an stops executing.

### Expected Behavior
The Script should run without problems.

### Steps to Reproduce
1. `terraform plan`
2. `terraform apply`

**Comment by smutel** [comment]
Hello,

As you can see in the `README`, the version of Netbox you are using is not compatible with this version of the provider.

For the moment this provider is only  compatible with Netbox 2.9. The provider is based on the [go-netbox](https://github.com/netbox-community/go-netbox) library which is not updated so often.

I am looking to create a fork of this library to be able to do update more often but it will take time to do it and to maintain it.

I let this issue opened to keep it in mind when a version compatible with Netbox 2.11 will be released.

If someone wants to help me to create and maintain a new repo with the go-netbox library I will be very happy.

**Comment by DefunctExodus** [comment]
> Hello,
> 
> As you can see in the `README`, the version of Netbox you are using is not compatible with this version of the provider.
> 
> For the moment this provider is only compatible with Netbox 2.9. The provider is based on the [go-netbox](https://github.com/netbox-community/go-netbox) library which is not updated so often.
> 
> I am looking to create a fork of this library to be able to do update more often but it will take time to do it and to maintain it.
> 
> I let this issue opened to keep it in mind when a version compatible with Netbox 2.11 will be released.
> 
> If someone wants to help me to create and maintain a new repo with the go-netbox library I will be very happy.

I have actually run into  the same problem with the Netbox library, I would be willing to help out with a fork of it. I was considering doing the same thing honestly
