### ISSUE TITLE
tagged_vlans field is not initializing correctly

### ISSUE THREAD

**Issue by smutel** [smutel/terraform-provider-netbox#78]
## Summary

After first apply, if we apply the code again terraform wants to update tagged_vlans field

### Netbox version

```paste below
v2.11.12
```

### Terraform version

```paste below
v1.0.9
```

### Provider version

```paste below
v2.0.2
```

### Affected Data(s) / Resource(s)

* resource netbox_virtualization_interface

### Terraform Configuration Files

```hcl
resource "netbox_virtualization_interface" "interface_test" {
  name              = "default"
  virtualmachine_id = netbox_virtualization_vm.vm_test.id
  mac_address       = "AA:AA:AA:AA:AA:AA"
  description       = "Interface de test"
}
```

### Terraform Output

```tf
resource "netbox_virtualization_interface" "interface_test" {
        id                = "1"
        name              = "default
      + tagged_vlans      = []
}  
```

### Actual Behavior

Terraform is displaying a change after the first apply.

### Expected Behavior

No change.

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

**Comment by amhn** [comment]
I think this issue can be closed. With netbox 3.2.9 and current master branch of terraform-provider-netbox the second `terraform apply` reports
```
No changes. Your infrastructure matches the configuration.
```
