### ISSUE TITLE
SHA256SUM incorrect for v0.2.1 ?

### ISSUE THREAD

**Issue by schmitmd** [smutel/terraform-provider-netbox#8]
Looks to me like something's wrong w/ the SHA256 sum for the latest release.  Works for 0.2.0, but not 0.2.1.
```
MYLAPTOP:~/terraform%>terraform init

Initializing the backend...

Initializing provider plugins...
- Finding smutel/netbox versions matching "0.2.1"...
- Installing smutel/netbox v0.2.1...

Error: Failed to install provider

Error while installing smutel/netbox v0.2.1: checksum list has unexpected
SHA-256 hash 8ce8649c524c56d6d46573f812e8ec75ed9b9a0b4a79edd3dc70deeed5f4c874
(expected 55679479c00d452a01cdae2519b110bf2ed2962364b50fa897e44dcb8daec255)

**Comment by schmitmd** [comment]
this is for amd64 linux, I didn't test any other architectures.

**Comment by smutel** [comment]
Hello,

Yes, there is an issue there. I will upload this version again tonight.

Regards.

**Comment by smutel** [comment]
Yesterday I updated the SHA256 file but it does not work.
I don't know if the terraform registry is storing this file by his own.
I opened this topic in the terraform community forum: https://discuss.hashicorp.com/t/sha256sums-on-terraform-registry/15900

**Comment by shamsway** [comment]
Wow, what a pain. FWIW, specifying `version = "0.2.0"` in the `required_providers` block is a workaround until terraform registry updates the SHA256 file.

**Comment by schmitmd** [comment]
Already did. :) Or you can download 2.1.0 and manually pop it out your terrafom plugins dir.

**Comment by smutel** [comment]
For info, I published a new release which is working with Netbox 2.9.
In addition some bugs resolved.
However no new resources / datas manged by this provider.
