### ISSUE TITLE
Error message when vcpus is not specified

### ISSUE THREAD

**Issue by smutel** [smutel/terraform-provider-netbox#82]
## Summary

Error message when vcpus is not specified in `resource_netbox_virtualization_vm`.

### Netbox version

```paste below
v2.11.12
```

### Terraform version

```paste below
v1.0.10
```

### Provider version

```paste below
v2.1.0
```

### Affected Data(s) / Resource(s)

* resource_netbox_virtualization_vm

### Terraform Configuration Files

```hcl
resource "netbox_virtualization_vm" "vm_test" {                                                     
  cluster_id  = data.netbox_virtualization_cluster.cluster_test.id                                  
  name        = "test"                                                                              
  disk        = 10                                                                                  
  memory      = 10                                                                                  
  platform_id = data.netbox_dcim_platform.platform_test.id                                          
  tenant_id   = netbox_tenancy_tenant.tenant_test.id                                                
  role_id     = 1
```

### Terraform Output

```paste below
Error: response status code does not match any response statuses defined for this endpoint in the swagger spec (status 400): {}
│ 
│   with netbox_virtualization_vm.vm_test,
│   on main.tf line 229, in resource "netbox_virtualization_vm" "vm_test":
│  229: resource "netbox_virtualization_vm" "vm_test" {
```

### Actual Behavior

Error message displayed, creation not done.

### Expected Behavior

No error message displayed, creation done.

### Steps to Reproduce

1. `terraform apply`

**Comment by duviful** [comment]
Hello,
i'm experiencing the same error:
`Error: response status code does not match any response statuses defined for this endpoint in the swagger spec (status 400): {}`

One further test i did was to import a manually created entry. The error i got was:
`Error: json: cannot unmarshal number into Go struct field VirtualMachineWithConfigContext.results.vcpus of type string`

Best.

**Comment by smutel** [comment]
Hello,

Sorry to hear that. I tried to update the go-netbox library https://github.com/smutel/go-netbox/tree/FixVcpusRemoved.
But when I tested it, it is not working as expected.
For the moment I don't have any good solution, I need to troubleshoot it more deeply.

**Comment by duviful** [comment]
No problem sir. 
Thank you for your work btw.

**Comment by rossigee** [comment]
fwiw, i was also getting the 400 errors in one case and was able to work around it by removing the existing record in Netbox and having TF recreate it.
