### ISSUE TITLE
Error message when fetching virtual machines (vcpus being number and not string)

### ISSUE THREAD

**Issue by vilhelmprytz** [smutel/terraform-provider-netbox#90]
## Summary

When I try to fetch all virtual machines from my Netbox installation, I get an error message where Go tries to convert a number (vcpus) into a string but fails to do so.

### Netbox version
```paste below
v2.10.6
```

### Terraform version

```paste below
Terraform v1.0.11
on linux_amd64
```

### Provider version

```paste below
+ provider registry.terraform.io/smutel/netbox v2.2.0
```

### Affected Data(s) / Resource(s)

* data netbox_json_virtualization_virtual_machines_list

### Terraform Configuration Files

```hcl
data "netbox_json_virtualization_virtual_machines_list" "test" {
  limit = 0
}
output "virtualmachines" {
  value = jsondecode(data.netbox_json_virtualization_virtual_machines_list.test.json)
}
```

### Terraform Output

```paste below
╷
│ Error: json: cannot unmarshal number into Go struct field VirtualMachineWithConfigContext.results.vcpus of type string
│ 
│   with data.netbox_json_virtualization_virtual_machines_list.test,
│   on terraform.tf line 71, in data "netbox_json_virtualization_virtual_machines_list" "test":
│   71: data "netbox_json_virtualization_virtual_machines_list" "test" {
│ 
```

### Actual Behavior

Unable to proceed with parsing data from Netbox.

### Expected Behavior

The expected behavior is that Terraform is able to convert numbers to strings.

### Steps to Reproduce

1. `terraform apply` or `terraform plan`

**Comment by smutel** [comment]
```v2.x.x (please let me know if you need something more specific)```
=> yes please

**Comment by vilhelmprytz** [comment]
@smutel I have updated the initial description with the correct version.

**Comment by smutel** [comment]
Please take a look at this: https://github.com/smutel/terraform-provider-netbox#compatibility-with-netbox
Your version is not supported.

You have two options:
* Upgrade your netbox instance to 2.11.x and use the version 2.x.y of the provider
* Try to use version 1.x.y but I can't be sure that it will work

**Comment by vilhelmprytz** [comment]
Ah, my bad! Thanks a lot for the quick response, will try upgrading to a supported version! Closing.
