### ISSUE TITLE
400 Error on creation of VM with custom fields

### ISSUE THREAD

**Issue by S0LERA** [smutel/terraform-provider-netbox#97]
## Summary
400 error when trying to apply a vm with **any type** of custom fields.

### Netbox version

```paste below
v3.1.9
```

### Terraform version

```paste below
1.1.7
```

### Provider version

```paste below
3.0.0
```

### Affected Data(s) / Resource(s)

* resource netbox_virtualization_vm

### Terraform Configuration Files

```hcl
resource "netbox_virtualization_vm" "vm_test" {
  name            = "TestVm"
  comments        = "VM created by terraform"
  vcpus           = 2
  cluster_id      = 6
  tenant_id = 10

  custom_field {
    name = "cf_boole"
    type = "boolean"
    value = "true"
  }
}
```

### Terraform Output

```paste below
Error: response status code does not match any response statuses defined for this endpoint in the swagger spec (status 400): {}
```

### Actual Behavior
Error message displayed, creation not done.

### Expected Behavior
No error message displayed, creation done.

### Steps to Reproduce
1. `terraform apply`

**Comment by smutel** [comment]
The provider version 3.0 is not compatible with Netbox 3.1.

**Comment by rossigee** [comment]
In case it helps, I'm running Netbox 3.1 with the 3.0 plugin. I found I needed to present `vcpus` as a string (just added quotes) instead of a number but otherwise it seems to work as expected.

Also, check whether `cf_boole` in your example isn't just a typo.
